# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-11 16:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('defines', '0002_load_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_port', models.IntegerField()),
                ('destination_port', models.IntegerField()),
                ('source_ip', models.CharField(max_length=15)),
                ('destination_ip', models.CharField(max_length=15)),
                ('is_run', models.BooleanField(default=False)),
                ('chain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_chain', to='defines.Chain')),
                ('protocol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_protocol', to='defines.Protocol')),
            ],
        ),
    ]

