# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-11 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defines', '0003_rule'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='command',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='rule',
            name='operation',
            field=models.CharField(default='ACCEPT', max_length=30),
            preserve_default=False,
        ),
    ]
