# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-11 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defines', '0004_auto_20180411_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='destination_ip',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='rule',
            name='destination_port',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rule',
            name='source_ip',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='rule',
            name='source_port',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
