# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-11 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defines', '0005_auto_20180411_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='command',
            field=models.TextField(blank=True, null=True),
        ),
    ]
