# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-11 20:29
from __future__ import unicode_literals

import defines.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defines', '0006_auto_20180411_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='rule',
            name='destination_ip',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[defines.validators.ip_validator]),
        ),
        migrations.AlterField(
            model_name='rule',
            name='source_ip',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[defines.validators.ip_validator]),
        ),
    ]
